#!/usr/bin/env npx tsx
/**
 * Generate E2E Test Report
 *
 * Combines CLI and MCP test results into a unified report.
 * Generates Markdown report for docs/ and JSON for programmatic use.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

// ESM compatibility for __dirname
const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const ROOT_DIR = join(__dirname, '..', '..')
const RESULTS_DIR = join(ROOT_DIR, 'test-results')
const DOCS_DIR = join(ROOT_DIR, 'docs', 'testing', 'results')

interface TestSummary {
  type: string
  timestamp: string
  duration: number
  exitCode: number
  passed: boolean
}

interface CombinedReport {
  timestamp: string
  cli: TestSummary | null
  mcp: TestSummary | null
  overall: {
    passed: boolean
    totalDuration: number
    testsRun: number
    testsPassed: number
    testsFailed: number
  }
  hardcodedIssues: HardcodedIssue[]
  baselines: Record<string, unknown>
}

interface HardcodedIssue {
  type: string
  pattern: string
  value: string
  command: string
  source: string
}

function loadSummary(filename: string): TestSummary | null {
  const path = join(RESULTS_DIR, filename)
  if (!existsSync(path)) {
    console.warn(`Summary not found: ${filename}`)
    return null
  }
  return JSON.parse(readFileSync(path, 'utf-8'))
}

function loadResults(filename: string): unknown | null {
  const path = join(RESULTS_DIR, filename)
  if (!existsSync(path)) {
    return null
  }
  try {
    return JSON.parse(readFileSync(path, 'utf-8'))
  } catch {
    return null
  }
}

function extractHardcodedIssues(results: unknown): HardcodedIssue[] {
  const issues: HardcodedIssue[] = []

  if (!results || typeof results !== 'object') {
    return issues
  }

  // Walk through results looking for hardcoded issue markers
  const walk = (obj: unknown, path = ''): void => {
    if (!obj || typeof obj !== 'object') return

    if (Array.isArray(obj)) {
      obj.forEach((item, i) => walk(item, `${path}[${i}]`))
      return
    }

    const record = obj as Record<string, unknown>

    if (record.hardcodedIssues && Array.isArray(record.hardcodedIssues)) {
      issues.push(...(record.hardcodedIssues as HardcodedIssue[]))
    }

    Object.entries(record).forEach(([key, value]) => {
      walk(value, path ? `${path}.${key}` : key)
    })
  }

  walk(results)

  return issues
}

function generateMarkdownReport(report: CombinedReport): string {
  const lines: string[] = []
  const date = new Date(report.timestamp).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  lines.push(`# E2E Test Results - ${date}`)
  lines.push('')
  lines.push('## Summary')
  lines.push('')
  lines.push(`- **Status**: ${report.overall.passed ? '✅ PASSED' : '❌ FAILED'}`)
  lines.push(`- **Total Duration**: ${(report.overall.totalDuration / 1000).toFixed(2)}s`)
  lines.push(`- **Generated**: ${report.timestamp}`)
  lines.push('')

  lines.push('## Test Results')
  lines.push('')
  lines.push('| Phase | Status | Duration |')
  lines.push('|-------|--------|----------|')

  if (report.cli) {
    const status = report.cli.passed ? '✅ Pass' : '❌ Fail'
    lines.push(`| CLI E2E | ${status} | ${(report.cli.duration / 1000).toFixed(2)}s |`)
  } else {
    lines.push('| CLI E2E | ⏭️ Skipped | - |')
  }

  if (report.mcp) {
    const status = report.mcp.passed ? '✅ Pass' : '❌ Fail'
    lines.push(`| MCP E2E | ${status} | ${(report.mcp.duration / 1000).toFixed(2)}s |`)
  } else {
    lines.push('| MCP E2E | ⏭️ Skipped | - |')
  }

  lines.push('')

  if (report.hardcodedIssues.length > 0) {
    lines.push('## Hardcoded Issues Detected')
    lines.push('')
    lines.push('| Type | Pattern | Value | Command |')
    lines.push('|------|---------|-------|---------|')

    for (const issue of report.hardcodedIssues) {
      lines.push(`| ${issue.type} | ${issue.pattern} | \`${issue.value}\` | ${issue.command} |`)
    }

    lines.push('')
    lines.push('> These issues should be resolved before Phase 5.')
    lines.push('')
  }

  if (Object.keys(report.baselines).length > 0) {
    lines.push('## Performance Baselines')
    lines.push('')
    lines.push('```json')
    lines.push(JSON.stringify(report.baselines, null, 2))
    lines.push('```')
    lines.push('')
  }

  lines.push('---')
  lines.push('')
  lines.push('*Generated by skillsmith E2E test suite*')

  return lines.join('\n')
}

async function main(): Promise<void> {
  console.log('📊 Generating E2E Test Report...\n')

  // Ensure directories exist
  if (!existsSync(DOCS_DIR)) {
    mkdirSync(DOCS_DIR, { recursive: true })
  }

  // Load summaries
  const cliSummary = loadSummary('cli-summary.json')
  const mcpSummary = loadSummary('mcp-summary.json')

  // Load detailed results for hardcoded issue extraction
  const cliResults = loadResults('cli-results.json')
  const mcpResults = loadResults('mcp-results.json')

  // Extract hardcoded issues
  const hardcodedIssues = [
    ...extractHardcodedIssues(cliResults),
    ...extractHardcodedIssues(mcpResults),
  ]

  // Calculate overall stats
  const totalDuration = (cliSummary?.duration ?? 0) + (mcpSummary?.duration ?? 0)
  const passed = (cliSummary?.passed ?? true) && (mcpSummary?.passed ?? true)

  const report: CombinedReport = {
    timestamp: new Date().toISOString(),
    cli: cliSummary,
    mcp: mcpSummary,
    overall: {
      passed,
      totalDuration,
      testsRun: 0, // Would need to parse detailed results
      testsPassed: 0,
      testsFailed: 0,
    },
    hardcodedIssues,
    baselines: {}, // Would be populated from baseline collector
  }

  // Write JSON report
  writeFileSync(join(RESULTS_DIR, 'combined-report.json'), JSON.stringify(report, null, 2))

  // Generate and write Markdown report
  const markdown = generateMarkdownReport(report)
  const dateStr = new Date().toISOString().split('T')[0]
  writeFileSync(join(DOCS_DIR, `e2e-results-${dateStr}.md`), markdown)
  writeFileSync(join(DOCS_DIR, 'latest-summary.md'), markdown)

  console.log('✅ Reports generated:')
  console.log(`   - ${join(RESULTS_DIR, 'combined-report.json')}`)
  console.log(`   - ${join(DOCS_DIR, `e2e-results-${dateStr}.md`)}`)
  console.log(`   - ${join(DOCS_DIR, 'latest-summary.md')}`)

  if (hardcodedIssues.length > 0) {
    console.log(`\n⚠️  ${hardcodedIssues.length} hardcoded issue(s) detected!`)
  }

  if (!passed) {
    console.log('\n❌ E2E tests failed')
    process.exit(1)
  }

  console.log('\n✅ E2E tests passed')
}

main().catch((error) => {
  console.error('Failed to generate report:', error)
  process.exit(1)
})
