#!/bin/bash
# Worktree Manager - Generate Claude Code launch script for a worktree
# Usage: ./generate-launch-script.sh <worktree-path> <issue-id> <title> <prompt-file>
#
# This generates a bash script that:
# 1. Navigates to the worktree
# 2. Syncs with main
# 3. Checks Docker container health
# 4. Displays the task prompt
# 5. Launches Claude Code

set -e

WORKTREE_PATH=$1
ISSUE_ID=$2
TITLE=$3
PROMPT_FILE=$4

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

print_error() {
    echo -e "${RED}✗${NC} $1" >&2
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

# Validation
if [ -z "$WORKTREE_PATH" ] || [ -z "$ISSUE_ID" ] || [ -z "$TITLE" ]; then
    echo "Usage: $0 <worktree-path> <issue-id> <title> [prompt-file]"
    echo ""
    echo "Arguments:"
    echo "  worktree-path  Path to the worktree directory"
    echo "  issue-id       Linear issue ID (e.g., SMI-619)"
    echo "  title          Short title for the task"
    echo "  prompt-file    Optional file containing the full prompt (reads from stdin if not provided)"
    echo ""
    echo "Examples:"
    echo "  $0 ../worktrees/smi-619 SMI-619 'CI/CD Docker' prompt.md"
    echo "  echo 'Configure CI/CD...' | $0 ../worktrees/smi-619 SMI-619 'CI/CD Docker'"
    exit 1
fi

# Get absolute path
WORKTREE_ABS=$(cd "$WORKTREE_PATH" 2>/dev/null && pwd) || {
    print_error "Worktree does not exist: $WORKTREE_PATH"
    exit 1
}

# Read prompt from file or stdin
if [ -n "$PROMPT_FILE" ] && [ -f "$PROMPT_FILE" ]; then
    PROMPT=$(cat "$PROMPT_FILE")
elif [ ! -t 0 ]; then
    PROMPT=$(cat)
else
    PROMPT="Execute $ISSUE_ID: $TITLE"
fi

# Determine output script path
SCRIPT_DIR=$(dirname "$WORKTREE_ABS")/scripts
mkdir -p "$SCRIPT_DIR"
SCRIPT_PATH="$SCRIPT_DIR/run-$(echo "$ISSUE_ID" | tr '[:upper:]' '[:lower:]').sh"

# Get branch name
BRANCH=$(cd "$WORKTREE_ABS" && git branch --show-current)

# Generate the script
cat > "$SCRIPT_PATH" << SCRIPT_EOF
#!/bin/bash
# $ISSUE_ID: $TITLE
# Auto-generated by worktree-manager
# Run this in a separate terminal session

set -e

WORKTREE="$WORKTREE_ABS"

echo "=== $ISSUE_ID: $TITLE ==="
echo ""
echo "Worktree: \$WORKTREE"
echo "Branch: $BRANCH"
echo ""

cd "\$WORKTREE"

# Sync with main before starting
git fetch origin main
git rebase origin/main || {
    echo "Rebase failed. Resolve conflicts and run this script again."
    exit 1
}

# Ensure Docker container is running (if docker-compose.yml exists in repo)
if [ -f "docker-compose.yml" ] || [ -f "compose.yml" ]; then
    echo "Checking Docker container..."
    if ! docker ps --filter name=skillsmith-dev-1 --format "{{.Status}}" 2>/dev/null | grep -q "Up"; then
        echo "Starting Docker container..."
        docker compose --profile dev up -d 2>/dev/null || docker-compose --profile dev up -d 2>/dev/null || true
        sleep 3
    fi
    echo "Docker container ready."
    echo ""
fi

echo "Starting Claude Code session..."
echo ""

# Display task prompt
cat << 'PROMPT'
================================================================================
$ISSUE_ID: $TITLE
================================================================================

## IMPORTANT: Use Docker Skill
Run /docker before executing any npm commands. All builds, tests, and commands MUST run in Docker container.

$PROMPT

## When Done
1. Commit with conventional commit message referencing $ISSUE_ID
2. Push: git push origin $BRANCH
3. Create PR
4. Update Linear: node ~/.claude/skills/linear/skills/linear/scripts/linear-api.mjs update-status --issue $ISSUE_ID --status done
================================================================================
PROMPT

# Launch Claude Code
claude
SCRIPT_EOF

chmod +x "$SCRIPT_PATH"
print_success "Generated: $SCRIPT_PATH"
echo ""
echo "Run in a new terminal:"
echo "  $SCRIPT_PATH"
