#!/usr/bin/env bash
#
# worktree-docker.sh - Docker helper for git worktrees
#
# Manages Docker containers in worktrees with unique names and ports
# to avoid conflicts with main repository containers.
#
# Usage: ./scripts/worktree-docker.sh <command> [worktree-path]
#
# Commands:
#   start     Start Docker containers in worktree
#   stop      Stop Docker containers in worktree
#   status    Show status of worktree containers
#   generate  Generate docker-compose.override.yml for worktree
#   ports     Show port mappings for worktree
#
# SMI-2160: Docker worktree configuration

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

#######################################
# Print usage information
#######################################
usage() {
    cat << EOF
Usage: $(basename "$0") <command> [worktree-path]

Docker helper for git worktrees with isolated containers.

Commands:
  start     Start Docker containers in worktree (docker compose up -d)
  stop      Stop Docker containers in worktree (docker compose down)
  status    Show status of worktree containers
  generate  Generate docker-compose.override.yml for worktree
  ports     Show port mappings for worktree

Arguments:
  worktree-path   Path to the worktree (default: current directory)

Examples:
  $(basename "$0") start ../worktrees/my-feature
  $(basename "$0") stop
  $(basename "$0") status ../worktrees/jwt-rollout
  $(basename "$0") generate ../worktrees/new-feature
  $(basename "$0") ports

Note:
  This script ensures each worktree has unique container names and ports
  to allow parallel Docker development across multiple worktrees.

EOF
}

#######################################
# Error handling
#######################################
error() {
    echo -e "${RED}Error: $1${NC}" >&2
    exit 1
}

info() {
    echo -e "${BLUE}$1${NC}"
}

success() {
    echo -e "${GREEN}$1${NC}"
}

warn() {
    echo -e "${YELLOW}$1${NC}"
}

#######################################
# Get worktree name from path
#######################################
get_worktree_name() {
    local worktree_path="$1"

    # Get branch name from worktree
    local branch_name
    branch_name=$(cd "$worktree_path" && git branch --show-current 2>/dev/null || echo "")

    if [[ -z "$branch_name" ]]; then
        # Fallback to directory name
        branch_name=$(basename "$worktree_path")
    fi

    # Sanitize for container name
    echo "$branch_name" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9-' '-' | sed 's/--*/-/g' | sed 's/^-//;s/-$//'
}

#######################################
# Generate docker-compose.override.yml
#######################################
cmd_generate() {
    local worktree_path="$1"

    if [[ ! -f "$worktree_path/docker-compose.yml" ]]; then
        error "No docker-compose.yml found in $worktree_path"
    fi

    local worktree_name
    worktree_name=$(get_worktree_name "$worktree_path")

    # Calculate port offset based on hash
    local port_offset
    port_offset=$(echo -n "$worktree_name" | cksum | awk '{print ($1 % 99) + 1}')

    local dev_app_port=$((3000 + port_offset * 10))
    local dev_mcp_port=$((3000 + port_offset * 10 + 1))
    local test_port=$((3000 + port_offset * 10 + 2))
    local orchestrator_port=$((3000 + port_offset * 10 + 3))

    info "Generating docker-compose.override.yml for: $worktree_name"

    cat > "$worktree_path/docker-compose.override.yml" << EOF
# Worktree-specific overrides (auto-generated by worktree-docker.sh)
# Container names and ports must be unique per worktree
# Worktree: $worktree_name
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

services:
  dev:
    container_name: ${worktree_name}-dev-1
    ports:
      - "${dev_app_port}:3000"   # Main app
      - "${dev_mcp_port}:3001"   # MCP server

  test:
    container_name: ${worktree_name}-test-1
    ports:
      - "${test_port}:3000"      # Test app

  orchestrator:
    container_name: ${worktree_name}-orchestrator-1
    ports:
      - "${orchestrator_port}:3000"  # Orchestrator
EOF

    success "Generated: $worktree_path/docker-compose.override.yml"
    echo ""
    echo "Port mappings:"
    echo "  dev app:       localhost:${dev_app_port}"
    echo "  dev MCP:       localhost:${dev_mcp_port}"
    echo "  test:          localhost:${test_port}"
    echo "  orchestrator:  localhost:${orchestrator_port}"
}

#######################################
# Start Docker containers
#######################################
cmd_start() {
    local worktree_path="$1"

    if [[ ! -f "$worktree_path/docker-compose.yml" ]]; then
        error "No docker-compose.yml found in $worktree_path"
    fi

    # Generate override if missing
    if [[ ! -f "$worktree_path/docker-compose.override.yml" ]]; then
        warn "No docker-compose.override.yml found. Generating..."
        cmd_generate "$worktree_path"
        echo ""
    fi

    info "Starting Docker containers..."
    (cd "$worktree_path" && docker compose --profile dev up -d)

    echo ""
    success "Docker containers started!"
    cmd_status "$worktree_path"
}

#######################################
# Stop Docker containers
#######################################
cmd_stop() {
    local worktree_path="$1"

    if [[ ! -f "$worktree_path/docker-compose.yml" ]]; then
        error "No docker-compose.yml found in $worktree_path"
    fi

    info "Stopping Docker containers..."
    (cd "$worktree_path" && docker compose --profile dev down)

    success "Docker containers stopped."
}

#######################################
# Show container status
#######################################
cmd_status() {
    local worktree_path="$1"

    local worktree_name
    worktree_name=$(get_worktree_name "$worktree_path")

    info "Container status for: $worktree_name"
    echo ""

    # Show containers matching worktree name
    docker ps -a --filter "name=${worktree_name}" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" 2>/dev/null || echo "No containers found"
}

#######################################
# Show port mappings
#######################################
cmd_ports() {
    local worktree_path="$1"

    if [[ ! -f "$worktree_path/docker-compose.override.yml" ]]; then
        warn "No docker-compose.override.yml found"
        return
    fi

    info "Port mappings from docker-compose.override.yml:"
    echo ""
    grep -E '^\s+-\s+"[0-9]+:' "$worktree_path/docker-compose.override.yml" | sed 's/^[[:space:]]*/  /'
}

#######################################
# Main entry point
#######################################
main() {
    if [[ $# -lt 1 ]]; then
        usage
        exit 1
    fi

    local command="$1"
    local worktree_path="${2:-.}"

    # Convert to absolute path
    if [[ ! "$worktree_path" = /* ]]; then
        worktree_path="$(cd "$worktree_path" 2>/dev/null && pwd)" || error "Invalid path: $worktree_path"
    fi

    case "$command" in
        start)
            cmd_start "$worktree_path"
            ;;
        stop)
            cmd_stop "$worktree_path"
            ;;
        status)
            cmd_status "$worktree_path"
            ;;
        generate)
            cmd_generate "$worktree_path"
            ;;
        ports)
            cmd_ports "$worktree_path"
            ;;
        -h|--help|help)
            usage
            exit 0
            ;;
        *)
            error "Unknown command: $command

Run '$(basename "$0") --help' for usage information."
            ;;
    esac
}

main "$@"
